FROM node:24-alpine AS build
WORKDIR /app
COPY . .
RUN npm install && npm run build

FROM node:24-alpine
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --only=production
COPY --from=build /app/dist ./dist
CMD [ "node", "dist/index.js" ]
