services:
  msgpostbot:
    image: msgpostbot
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
    develop:
      watch:
        - path: ./package.json
          action: rebuild
        - path: ./package-lock.json
          action: rebuild
        - path: ./
          target: /app
          action: sync
